baseUrl:             https://tokariew.xyz
title:               tokariew.xyz
languageCode:        en-gb
theme:               smol
paginate:            16
summaryLength:       48
listPaginate:        16
enableGitInfo: true
params:
    contentTypeName: posts
    subtitle:        Thoughts of unorganized person
    dateFmt:         2006-01-02

author:
  name: Tokariew

taxonomies:
  tag: tags

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
include_toc: true

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml
outputFormats:
  Atom:
    mediaType: application/atom+xml
    baseName: atom
    isPlainText: false

outputs:
  home:
    - HTML
    - Atom

menu:
    main:
      - identifier:  posts
        name:        Posts
        url:         /posts
        weight:      1
      - identifier:  tags
        name:        Tags
        url:         /tags
        weight:      3
      - identifier:  about
        name:        About
        url:         /about
        weight:      4
      - identifier:  books
        name:        Books
        url:         /books
    footer:
      - identifier:  github
        name:        Github
        url:         https://github.com/tokariew
      - identifier:  nextcloud
        name:        Nextcloud
        url:         /nextcloud

